CURSOR_ENABLED_DEFAULT = False

# Cursor smoothing
F_MIN = 1
BETA = 4
D_CUTOFF = 0.5

# Pinch
PINCH_THRESHOLD = 0.035
RELEASE_THRESHOLD = 0.045

# Cursor Sensitivity
X_MIN = 0.30
X_MAX = 0.70
Y_MIN = 0.30
Y_MAX = 0.70

# Swipe
SWIPE_DISTANCE = 0.08
SWIPE_MAX_TIME = 0.2
SWIPE_MIN_SPEED = 1.0
SWIPE_COOLDOWN = 0.8

# Inertial scroll
SCROLL_INITIAL_SPEED = 4000.0
SCROLL_DECAY = 3

# Cursor toggle
CURSOR_HOLD_TIME = 0.5
CURSOR_RELEASE_FRAMES = 5

# Semantic gestures
MIC_HOLD_TIME = 0.2
SEND_HOLD_TIME = 0.2
MIC_RELEASE_FRAMES = 5
MIC_GLOBAL_COOLDOWN = 0.3
COMMAND_RELEASE_FRAMES = 5